#!/bin/bash
if [ -z "$1" ]
then
    echo "No argument supplied"
    exit 0
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FILEPATH=$1
FILENAME="${FILEPATH##*/}"
CLASSNAME="${FILENAME%%.*}"
OUTPUT=$(cat $FILEPATH)

# Don't turn into protected class for codeforces
if [[ $CLASSNAME != cf* ]] && [[ $CLASSNAME != CF* ]] ; then
OUTPUT=$(echo "$OUTPUT" | sed "s/public class $CLASSNAME/class Main/g")
fi

#Transform classname into main
OUTPUT=$(echo "$OUTPUT" | sed "s/$CLASSNAME/Main/g")


echo "$OUTPUT" > $DIR/../output/Main.java


